import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased h-screen`}
      >
      <nav className="w-full h-1/12 bg-red-600 flex justify-start items-center ">
          <div className="flex items-center m-2">
          <h1 className="bg-white rounded-4xl p-1 mr-1">❤️</h1>
          <h1 className="font-bold text-xl">BloodLife Portal</h1>
          </div>
          
      </nav>
      <main className="w-full h-11/12 bg-white">
      {children}
      </main>
        
      </body>
    </html>
  );
}
